### ISSUE TITLE
How to compile executable

### ISSUE THREAD

**Issue by Abraham313** [PA-R29sY2F0bG1hbg/RansomeWare#1]
Can give a details  about How to compile executable.please.
If you can please,add a option that will create   readme.txt files with message in Every Driver including Desktop.
Kind regards

**Comment by PA-R29sY2F0bG1hbg** [comment]
i working on the compilation.
i meet some issue with pyinstaller for compile with external element (img),
since i rewrite the code in python 3.x and use the latest update of pyinstaller.

And for your next request. yay why not. i will build this when i finish some few other major update.

**Comment by PA-R29sY2F0bG1hbg** [comment]
Hi @Abraham313 , for compile Dogma use auto-py-to-exe.

>pip install auto-py-to-exe
>cmd auto-py-to-exe

That start web local app and insert manually the visual datas. this tool is very 
explicit. let me know if you meet some issue.
